### ISSUE TITLE
Add Type State builders

### ISSUE THREAD

**Issue by Techassi** [stackabletech/operator-rs#607]
This issue tracks the effort to implement the type state pattern for all builders across `operator-rs`. This involves updating multiple builders, adjusting tests and updating all product operators.

Additionally, an upstream PR in [typed_builder](https://github.com/idanarye/rust-typed-builder) should make it suitable to implement the pattern automatically with derive macros.

```[tasklist]
### Tasks
- [ ] [typed_builder](https://github.com/idanarye/rust-typed-builder) upstream PR
- [ ] Evaluate typed_builder for our usecases
- [ ] Implement pattern across all builders. This includes method renaming
```
